#!/bin/bash

HOOKS="$(dirname `readlink -f $0`)"
ROOT="$(dirname $HOOKS)"
SOURCE="$(dirname $ROOT)/app"
REPO="$(dirname $ROOT)/app.git"

cd $SOURCE

docker-compose down

cd $REPO

GIT_WORK_TREE="$SOURCE" git checkout -f

cd $SOURCE

docker-compose up -d
