#!/bin/bash

HOOKS="$(dirname `readlink -f $0`)"
ROOT="$(dirname ${HOOKS})"
SOURCE="$(dirname ${ROOT})/app"
REPO="$(dirname ${ROOT})/app.git"

docker-compose down --workdir="${SOURCE}"

GIT_WORK_TREE="${SOURCE}" git checkout -f

docker-compose up -d --workdir="${SOURCE}"
