#!/bin/bash

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ "master" == "$branch" ]; then

      BASE='<?php echo $base; ?>'
      DOMAIN='<?php echo $domain; ?>'
      APP="${BASE}/app/${DOMAIN}"

      if [ -f "${APP}/.new" ]; then
        rm -f "${APP}/.new"
        GIT_WORK_TREE="${APP}" git checkout -f
        exit
      fi

      main="${BASE}/sm/docker/docker-compose.yml"
      file="${BASE}/app/${DOMAIN}/docker-compose.yml"

      if [ "$(docker ps -q -f name=<?php echo $network; ?>)" ]; then
        if [ -f "${APP}/.hooks/before.sh" ]; then
          docker exec <?php echo $network; ?> sh /var/www/app/.hooks/before.sh
        fi
        docker-compose -f ${main} down
        docker-compose -f ${file} down
      fi

      GIT_WORK_TREE="${APP}" git checkout -f

      if [ -f "${file}" ]; then
        docker-compose -f ${file} up -d
        docker-compose -f ${main} up -d
        if [ -f "${APP}/.hooks/after.sh" ]; then
          docker exec <?php echo $network; ?> sh /var/www/app/.hooks/after.sh
        fi
      fi

    fi
done
