#!/bin/bash

BASE='<?php echo $base; ?>'
DOMAIN='<?php echo $domain; ?>'
APP="${BASE}/app/${DOMAIN}"

if [ -f "${APP}/.new" ]; then
  rm -f "${APP}/.new"
  GIT_WORK_TREE="${APP}" git checkout -f
  exit
fi

main="${BASE}/sm/docker/docker-compose.yml"
file="${BASE}/app/${DOMAIN}/docker-compose.yml"

if [ -f "${file}" ]; then
  docker-compose -f ${main} down
  docker-compose -f ${file} down
fi

GIT_WORK_TREE="${APP}" git checkout -f

if [ -f "${file}" ]; then
  docker-compose -f ${file} up -d
  docker-compose -f ${main} up -d
fi

if [ -f "${APP}/.hooks/install.sh" ]; then
  docker exec <?php echo $network; ?> sh /var/www/app/.hooks/install.sh
fi

