version: '3'

networks:
  <?php echo $network; ?>: # don't change
    driver: bridge

services:
<?php echo "  {$network}:"; ?> # don't change
    container_name: <?php echo $network; ?> # don't change
    networks:
      - <?php echo $network; ?> # don't change
    image: nginx:1.12
    restart: always
    volumes:
      - .:/usr/share/nginx/html/
    expose:
      - "80"
