#!/bin/bash

BASE='<?php echo $base; ?>'
DOMAIN='<?php echo $domain; ?>'
file='docker-compose.yml'

docker-compose -f ${BASE}/docker/${file} down
docker-compose -f ${BASE}/${DOMAIN}/app/${file} down

GIT_WORK_TREE="${BASE}/${DOMAIN}/app" git checkout -f

docker-compose -f ${BASE}/${DOMAIN}/app${file} -p p<?php echo $id; ?>_ up -d
docker-compose -f ${BASE}/docker/${file} up -d
