version: '3'

networks:
<?php
foreach($sites as $site) {
  echo "  {$site->network}_proxy:", PHP_EOL,
       "     external:", PHP_EOL,
       "       name: p{$site->id}_{$site->network}", PHP_EOL;
}
?>

services:
  proxy:
    build: ./
    networks:
<?php
foreach($sites as $site) {
  echo "      - {$site->network}_proxy", PHP_EOL;
}
?>
    ports:
      - 80:80
    volumes:
      - ./enabled:/etc/nginx/sites-enabled
