version: '3'

networks:
<?php
foreach($sites as $site) {
  $project = str_replace('_', '', $site->network);
  $name = "{$project}_{$site->network}";
  echo "  {$site->network}_proxy:", PHP_EOL,
       "     external:", PHP_EOL,
       "       name: {$name}", PHP_EOL;
}
?>

services:
  proxy:
    build: ./
    networks:
<?php
foreach($sites as $site) {
  echo "      - {$site->network}_proxy", PHP_EOL;
}
?>
    ports:
      - 80:80
    volumes:
      - ./enabled:/etc/nginx/sites-enabled
